version: 0.1.{build}-{branch}
configuration:
- Debug
- Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  APPVEYOR_RDP_PASSWORD:
    secure: MatkZGLF77XirWtOwTq5GA==
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build -c %CONFIGURATION% --version-suffix %LABEL% -v minimal
after_build:
- dotnet pack "src\NHamcrest.XUnit" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet test -c %CONFIGURATION% --no-build "src\NHamcrest.Tests\NHamcrest.Tests.csproj"
artifacts:
- path: artifacts\**\*.*
